### ISSUE TITLE
Docker Compose - Couchpotato not reachable

### ISSUE THREAD

**Issue by JanZHH** [RolfKoenders/potato#14]
I am trying to get the Mr. Potato Container working in a docker-compose.yml file together with couchpotato and some other services.

All services in this file share the same docker network and are reachable though their internal dns name.
Mr. Potato is not able to reach my couchpotato container...

Here is the part of the docker-compose.yml:
```yaml
mrpotato:
      image: rolfkoenders/potato:latest
        container_name: mrpotato
        env_file: uidgid.env
        environment:
            - CB_SLACK_KEY=xoxb-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            - CB_SLACK_NAME=mr_movie
            - CB_HOST=couchpotato
            - CB_PORT=5050
            - CB_COUCH_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        restart: always 
```
